### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by lmtat** [lokanx/fitbit-oauth2-client#1]
I have a Vue.js application
after i put the following line in main.js
`const {Fitbit, FileTokenManager} = require( 'fitbit-oauth2-client' );`
I got the following errors

` ERROR  Failed to compile with 6 errors                                                                                                          10:48:16 PM
 error  in ./node_modules/simple-oauth2/lib/client/client.js

Module parse failed: Unexpected character '#' (19:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| module.exports = class Client {
>   #config = null;
|   #client = null;
|

 @ ./node_modules/simple-oauth2/lib/client/index.js 3:15-34
 @ ./node_modules/simple-oauth2/index.js
 @ ./node_modules/fitbit-oauth2-client/Fitbit.js
 @ ./node_modules/fitbit-oauth2-client/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.137:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/simple-oauth2/lib/client/request-options.js

Module parse failed: Unexpected character '#' (28:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class RequestOptions {
>   #config = null;
|   #requestOptions = null;
|

 @ ./node_modules/simple-oauth2/lib/client/index.js 5:68-96
 @ ./node_modules/simple-oauth2/index.js
 @ ./node_modules/fitbit-oauth2-client/Fitbit.js
 @ ./node_modules/fitbit-oauth2-client/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.137:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/simple-oauth2/lib/client-credentials-grant-type.js

Module parse failed: Unexpected character '#' (7:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| module.exports = class ClientCredentials {
>   #config = null;
|   #client = null;
|

 @ ./node_modules/simple-oauth2/index.js 7:35-81
 @ ./node_modules/fitbit-oauth2-client/Fitbit.js
 @ ./node_modules/fitbit-oauth2-client/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.137:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./node_modules/simple-oauth2/lib/resource-owner-password-grant-type.js

Module parse failed: Unexpected character '#' (7:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| module.exports = class ResourceOwnerPassword {
>   #config = null;
|   #client = null;`

**Comment by lokanx** [comment]
Hi!
This library is nodejs only, building for browser will simply not work.

Cheers
